- title: Journal Reviewer
  type: services_list
  contents:
    - title:
      items:
        - Transactions on Neural Networks and Learning Systems (TNNLS)
        - Neural Networks
        - Neurocomputing
        - Cognitive Computation

- title: Conference Reviewer
  type: services_list
  contents:
    - title:
      items:
        - ACM SIGKDD Conference on Knowledge Discovery and Data Mining (KDD) 2024
        - International Conference on Pattern Recognition (ICPR) 2024